# Generated by Django 2.2.7 on 2019-11-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatPlayerDo', models.CharField(max_length=10)),
                ('battle_status', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
        ),
    ]
